### ISSUE TITLE
Diplsay counselling points for old sickle cell (disease/trait) adolescent and create followup for the sickle cell disease.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#100]
If there is an old student of sickle cell and fills the new baseline then counselling does not appear,Follow up of the disease and trait of the disease does not appear. 

Trait - Counselling Points 
Disease - Counselling Points and Followup Visit

**Tech analysis**

- [x] "Sickling test status" is not displayed again in Baseline/Endline if "Sickling test result" is answered once. 
- [x] But the corresponding counselling points should be displayed even if this is answered in any of the previous encounters. Currently it is displayed only when it is answered in the same encounter. Counselling points form element group is separate for "Trait" & "Disease"
- [x] Similarly, "Sickle Cell Disease Follow-up" visit should be scheduled if it is answered as "Disease" in any of the previous encounter or in the same encounter. Currently, it is scheduled only when it is answered in the same encounter.
- [x] The above changes need to be made in Baseline/Endline both wherever applicable.

**Comment by Dinesh2019** [comment]
@vedant After the endline is completed the baseline is not getting scheduled.
