### ISSUE TITLE
Baseline/Endline Form: UAT Feedback

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#106]
- [x] 1. Do you suffer from itching in the perenial area?" should be a female specific question in **Baseline and Endline form** under sexual details.

**Tech tasks**
"Do you suffer from itching in the perenial area?" under Sexual Medical History, add a rule to display only when the gender is female.
This needs to be updated in both **Baseline and Endline form**

-------------

- [x] 2. All values, statuses should be in red incase of severe cases in both **Baseline and Endline form**.

Obese (mild, moderate, severe), severe anemia, overweight, and severe malnutrition's values and status should be in red, while filling out the form, in the program summary, after submitting the form and in profile summary in both **Baseline and Endline form**.

**Tech tasks**

- [x] Mark abnormal following answer options of Question ""Nutritional status as per WHO""  - Mild Obese, Moderate Obese, Severe Obese and Severe Malnourished
- [x] Check in decision & program summary, all of the mentioned statuses should appear in red color.

----------------

- [x] 3. Set counseling points as per WHO nutritional status in both **Baseline and Endline form**.

- [x] If Obsese (Mild, Moderate, Severe) display obesity counselling points.
- [x]  If Severe Malnutrition, display severe malnutrition counselling points.

**Tech tasks**
Add skip rule on Baseline/Endline >> Counselling points >> Form element Group
If "Nutritional status as per WHO" is Mild Obese or Moderate Obese or Severe Obese then display Obesity related counselling points (Remove the logic based on BMI)
Similarly if "Nutritional status as per WHO" is Severe Malnourished then display Malnourished related counselling points (Remove the logic based on BMI)

**Comment by vedfordev** [comment]
@kameshbhariya @nupoorkhandelwal I checked there are counselling points related to **malnutrition** not **Malnutrition** and as per **Nutritional status as per WHO** cocept we have **malnourished** related answer. check and let me know.  Meanwhile move card to on hold.
