### ISSUE TITLE
[Adolescent Sewa Rural]: App changes to production org

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#108]
- [x] Upload the bundle into Adolescent Sewa Rural Production from ADSR UAT
- [ ] Please make sure the below epic changes are tested and moved to production.
- [ ] [Epic 1](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/adolescent-sewa-rural/44)
- [ ] [Epic 2](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/adolescent-sewa-rural/56)
- [ ] [Epic 3](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/adolescent-sewa-rural/54)
- [ ] [Epic 4](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/adolescent-sewa-rural/99)
- [ ] [Translations to be uploaded in production.](https://drive.google.com/file/d/1PRvNPcs_vD8ORjtEurGof4HG6_uKE6i9/view?usp=drive_link)

**Comment by Dinesh2019** [comment]
Translation missing in program summary

<img width="385" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXlYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24027cf43373bf859080e8f3e8910f1bd9d97bf3/Screenshot%202024-06-27%20at%202.12.26%E2%80%AFPM.png" alt="Screenshot 2024-06-27 at 2.12.26 PM.png" />

The nutrition status as per WHO is missing 

<img width="385" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNStYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b94fa33c8b5d200725ee413a355924e6cd1237a8/Screenshot%202024-06-27%20at%202.13.44%E2%80%AFPM.png" alt="Screenshot 2024-06-27 at 2.13.44 PM.png" />

Referral reason option is also missing in the translation

<img width="385" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlNYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f5b54c99253280158e9c639e10b367a89ee65ed2/Screenshot%202024-06-27%20at%202.14.37%E2%80%AFPM.png" alt="Screenshot 2024-06-27 at 2.14.37 PM.png" />


- [ ] Sickle Cell Disease Follow-up Encounter translation is missing 
- [ ] Sickle Cell Disease Follow-up Encounter Cancellation
