### ISSUE TITLE
[ADSR Support] Misc issues reported via support ticket

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/Adolescent-Sewa-Rural#11]
support tickets: there are currently 3 tickets on which Avni team has to work:

- [x] 2894: The sickle test result should get auto-populated in every future form once the test result is captured. As the sickle test is done once in a lifetime, this question should not be asked again once the test result is updated. 
Note: result options do not impact the above scenario.

**Tech tasks** -- 

- [x]  If "Sickling test result" has been answered once, it should not show up in any of the next visits (Annual Visit - Baseline Encounter, Annual Visit - Endline Encounter)

- [x]  If "Menstruation started" has been answered as "Yes" once, then "Menstruation started?" and "Age at Menarche" should not show up in any of the next visits (Annual Visit - Baseline Encounter, Annual Visit - Endline Encounter)

Also, update the subsequent fields skip rule to check the latest value in the entire program and show/hide respectively.
The remaining question on the female medical history should be shown if Menstruation started is marked as yes in any of the previous encounters.

--------------------------------------------------------------------------------------------------------------------

- [x] 2234: Chronic sickness visits are getting scheduled without reporting any disease. Re-check the following logic -

**Tech analysis** - 
seems the following check in the visit scheduling is not working properly, need to investigate -

```
const chronicSickness = programEncounter.getObservationReadableValue("Is there any other condition you want to mention about him/her");


      if (!_.includes(chronicSickness, 'No problem')) {
```

**Comment by vedfordev** [comment]
## Developer Note:

#### 2894:
for both,I checked there was already condition in **Annual Visit - Endline Encounter**. SO, Added same condition.


#### 2234 :
Checked with rule. rule is working properly.

**Comment by vedfordev** [comment]
requirements are not cleared.

**Comment by Dinesh2019** [comment]
- [ ] Sickle is selected once then it not showing in the rest of the encounters for example if I select the option for sickle as disease it is not showing in endline and also in the next year's baseline also 
- [x] Unable to select the option as yes for this question "Menstruation started' in the cilent app 

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmFjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d25e5719e114c21e35874d7ddacbb323f178923d/Screen%20Recording%202024-02-29%20at%209.01.31%E2%80%AFAM.mov

**Comment by Gojo-Taqi** [comment]
As for the first point, that is the requirement, if Sickling test status is marked "Done" in any of the encounters, then it will not come up in any of the encounters.
The second issue has been fixed.
Moving the card to QA ready.
