### ISSUE TITLE
Baseline/Endline Form - Under Sexual Details - Do you suffer from itching in the perenial area? should be applicable for all the genders.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#112]
- [x] Baseline/Endline - Under Sexual Details -Do you suffer from itching in the perenial area?
- [x] Remove skip logic from this question.
- [x] This question should be applicable to all genders and not specific to female.

**Comment by Dinesh2019** [comment]
@adamsanadi6  tested in UAT looks good you can upload the bundle in prod

**Comment by adamsanadi6** [comment]
@Dinesh2019 I uploaded the bundle, and now you can test it out.

**Comment by Dinesh2019** [comment]
@kameshbhariya @adamsanadi6 tested in prod and it looks good.
