### ISSUE TITLE
[ADSR] Improve offline dashboard performance

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/Adolescent-Sewa-Rural#113]
Changes are on prerelease
Below suggested changes needs to be made in the following existing cards so that the performance of the dashboard improves -

- [ ] Note down the run time before and after improving performance of each of the card 
- [ ] Replace filter with .filtered("SUBQUERY as given in the following query for dashboard card "Adolescents who dropped out of school"

```
let filtered = db
            .objects("ProgramEncounter")
            .filtered("programEnrolment.individual.voided = false AND programEnrolment.voided = false AND programEnrolment.program.name = 'Adolescent' AND programEnrolment.programExitDateTime = null AND voided = false AND encounterDateTime <> null AND (encounterType.name = 'Annual Visit - Baseline' OR encounterType.name = 'Annual Visit - Endline')")
            .filtered('TRUEPREDICATE sort(programEnrolment.individual.uuid asc , encounterDateTime desc) Distinct(programEnrolment.individual.uuid)')
            .filtered("SUBQUERY(observations, $observation, $observation.concept.uuid = '9705f6ad-50e1-4179-aa60-922014d7cc3c' and $observation.valueJSON CONTAINS 'fb1080b4-d1ec-4c87-a10d-3838ba9abc5b').@count > 0");
```

List of the cards -

- [x] Adolescents exited
- [x] Adolescents having sickle cell disease.
- [x] Adolescents having chronic sickness
- [x] Adolescents absent due to menstrual disorders
- [x] Active adolescent
- [x] Adolescents who dropped out of school
- [x] Adolescents having addiction
- [x] Adolescents having severe malnutrition
- [x] Adolescents with severe anaemia.
- [x] Adolescents having moderate anaemia.
- [ ] Total children for whom all vulnerability visits are completed
- [x] Village Adolescents to be Exited
- [x] School Adolescents to be Exited
- [x] Boarding Adolescents to be Exited

**Comment by nupoorkhandelwal** [comment]
```
let filtered = db
            .objects("ProgramEncounter")
            .filtered("programEnrolment.individual.voided = false AND programEnrolment.voided = false AND programEnrolment.program.name = 'Adolescent' AND programEnrolment.programExitDateTime = null AND voided = false AND encounterDateTime <> null AND (encounterType.name = 'Annual Visit - Baseline' OR encounterType.name = 'Annual Visit - Endline')")
            .filtered('TRUEPREDICATE sort(programEnrolment.individual.uuid asc , encounterDateTime desc) Distinct(programEnrolment.individual.uuid)')
            .filtered("SUBQUERY(observations, $observation, $observation.concept.uuid = '9705f6ad-50e1-4179-aa60-922014d7cc3c' and $observation.valueJSON CONTAINS 'fb1080b4-d1ec-4c87-a10d-3838ba9abc5b').@count > 0");
```

**Comment by Dinesh2019** [comment]
Test the report to which the master catchment has the high data 

Scenario 1: with master catchment 

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3V6QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--95edfaa283a05eb5b1785b45f22f074958a83c70/My%20Movie.mp4

Scenario 2 : with another catchment 

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEN6QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bcbbf729f8204ea62c08d173dd251d397f213a3b/My%20Movie.mp4
