### ISSUE TITLE
[ADSR] Add some checks and a logic on Baseline Cancel scenario

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/Adolescent-Sewa-Rural#117]
[Requirement Document](https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit?gid=250931016#gid=250931016)

Note - Update visit scheduling requirement sheet accordingly

### Tech tasks -

- [x] Under Endline completition - add a check if Baseline for the next year is already scheduled, do not schedule again
- [x] Under Endline cancellation - add a check if Baseline for the next year is already scheduled, do not schedule again
- [x] Under Baseline Cancellation - Add a visit schedule to schedule Baseline for the next year, also check that the individual is not exited and same visit is not already scheduled.

**Comment by adamsanadi6** [comment]
Backup:
[Old Visit Schedule Rule.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejN6QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e91f1212847cca89c5f1202d8d24848f3fed03ce/Old%20Visit%20Schedule%20Rule.zip)

**Comment by Dinesh2019** [comment]
Refrences video : 

[Video link](https://drive.google.com/file/d/1Qf4-Zx3h3IiTqyeaC5mtkhYcpgTyyqIK/view?usp=drive_link)
