### ISSUE TITLE
Remove "Mental Helath Followup" form from unplanned visit.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#119]
- [x] Remove "Mental Helath Followup" form from unplanned visit.

**Comment by Dinesh2019** [comment]
QA Reference video : 

[Click here for video](https://drive.google.com/file/d/1HTXOidbOU_7jVIXHMtIHh5zRIPpMvBVq/view?usp=drive_link)
