### ISSUE TITLE
Feedback from Sewa Rural on Anemia logic changes acceptance

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/Adolescent-Sewa-Rural#14]
## Context

- We have updated the Anemia logic in the app, but counselling  points are reflecting as per old logic. so we have to change the skip logics for the counselling point which are showing on the basis of HB range.
- We did the changes in the anaemia as a part this card [Link](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/adolescent-sewa-rural/6)

**Updated logic**
Hb < 8	Severe Anemia
Hb >= 8 and less than 11	Moderate Anemia
Hb >= 11 and less than 12	Mild Anemia
Hb greater than or equal to 12	Non anemic

## Acceptance Criteria
- In Annual Visit - Baseline Encounter --> Counselling for severe anaemia should shows only HB is less than 8.
- In Annual Visit - Baseline Encounter --> Counselling for moderate anaemia should shows only Hb >= 8 and less than 11
- Annual Visit - Endline Encounter --> Counselling for severe anaemia should shows only HB is less than 8.
- Annual Visit - Endline Encounter --> Counselling for moderate anaemia should shows only Hb >= 8 and less than 11

## Technical Approach

- [x] In these forms we have added the logic on the FEG so update the logic there
- [x] Check the FE if logic is there then update that logic as well.(some FE has a skip logic)

**Comment by Dinesh2019** [comment]
Test prod and UAT
