### ISSUE TITLE
Add worklist

### ISSUE THREAD

**Issue by vedfordev** [avniproject/Adolescent-Sewa-Rural#17]
**Ticket :** https://avni.freshdesk.com/a/tickets/2895

## Context :
Currently user is not able to proceed to direct enrolment screen and from enrolment to annual visit encounter. 

## Dev Task :
- [x] write worklist rule for enrolment.
- [x] write worklist rule for encounter.

**Comment by Dinesh2019** [comment]
@vedfordev if we edit the individual then it shows the option as save and register to the another individual is there a way to fix it if editing the individual where the baseline is scheduled only shows the option as save and the previous

**Comment by vedfordev** [comment]
@Dinesh2019 no

**Comment by vedfordev** [comment]
@Dinesh2019 moved changes to prod
