### ISSUE TITLE
[ADSR Support] Fix Severe Malnutrition visit scheduling

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/Adolescent-Sewa-Rural#19]
## Support ticket
https://avni.freshdesk.com/a/tickets/3491

## Context
Though currently there are no cases where a wrong Malnutrition is scheduled for any adolescent. But the followups should be scheduled only after checking the latest value of BMI, currently followup and cancel visit scheduling needs to be updated accordingly.

## Tech tasks

- [x] Update visit scheduling rules here to check the latest BMI in the entire enrolment before scheduling the next followup-
       1. Severe Malnutrition Follow-up Encounter
       2. Severe Malnutrition Follow-up Encounter Cancellation

**Comment by nupoorkhandelwal** [comment]
with aggregate_data as (select program_enrolment_id, "BMI (kg/m²)", encounter_date_time
                        from adsr.individual_adolescent_annual_visit_baseline
                        where encounter_date_time is not null

                        union all

                        select program_enrolment_id, "BMI (kg/m²)", encounter_date_time
                        from adsr.individual_adolescent_annual_visit_endline
                        where encounter_date_time is not null)
select data.program_enrolment_id, enc.earliest_visit_date_time, enc.created_date_time,enc.cancel_date_time
from (select row_number() OVER (PARTITION BY program_enrolment_id ORDER BY encounter_date_time desc) visit_number,
             program_enrolment_id,
             "BMI (kg/m²)"
      from aggregate_data) data
 join adsr.individual_adolescent_severe_malnutrition_followup enc on enc.program_enrolment_id = data.program_enrolment_id
 left join adsr.individual_adolescent_severe_malnutrition_followup cancel on cancel.id = enc.id
where "BMI (kg/m²)" > 14.5 and visit_number = 1
  and cancel.id is  null and enc.encounter_date_time is null;

**Comment by Gojo-Taqi** [comment]
Found an error while uploading bundle.
Have created a ticket and assigned it to the product team.
https://avni.freshdesk.com/a/tickets/3521

**Comment by Dinesh2019** [comment]
- [ ] After completing the end line as BMI value as >14.5 and again if we complete the BM value as <=14.5 in the baseline the sever malnutrition is not scheduled as per the requirement

**Comment by Dinesh2019** [comment]
- [ ] After completing the end line as BMI value as >14.5 and again if we complete the BM value as <=14.5 in the baseline the sever malnutrition is not scheduled as per the requirement

**Comment by Dinesh2019** [comment]
No Fix needed works as expected
