### ISSUE TITLE
[SR Card 3] Add program exit details via script for individuals on shared locations

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/Adolescent-Sewa-Rural#23]
## Context
SR is no more continuing their intervention at some of the schools, hence they do not want to continue monitoring individual enrolments at those schools

## Tech tasks

- [x] 1. Via script mark all the program enrolments under following locations as Exited ie. add program exit date, 01-01-2024, and exit observations as "Reason for exit" as "Change of school out of intervention area"
2.List of school provided by Sewa Rural -
Jhagadia kanya shala,Jhagadia Branch Shala,Jhagadia kumar shala, Ranipura primary school,Limodra primary school

Need to confirm - 
Zagadiya Kanya Primary, Jhagadiya branch primary, Zagadiya Kumar Primary, Ranipura P.S., Limbodara Primary

**Comment by adamsanadi6** [comment]
update
	public.program_enrolment as enrl
set
	program_exit_observations = enrl.program_exit_observations || jsonb_build_object('55454f19-f84e-4be4-afe8-c20a6ed6576a', '"5c74a9c0-659e-4915-b8fd-d0203da0d3a0"'),  
	last_modified_date_time = current_timestamp + ((enrl.id % 1000) * interval '1 millisecond'),
	program_exit_date_time = current_timestamp + ((enrl.id % 1000) * interval '1 millisecond'),
	last_modified_by_id = 10366,
	manual_update_history = enrl.manual_update_history || ', Updating the program decision concept Current Standard for old data as per #23 card'
from
	public.individual i
left join address a on
	a.id = i.address_id
left join public.address_level al on
	al.id = a."School id"
where
	i.is_voided = false
	and enrl.is_voided = false
	and i.id = enrl.individual_id
	and al.type_id = 715 -- al.type_id = 1307 for UAT
	and enrl.program_exit_date_time is null
	and al.title in ('Rajpardi Kanya Primary', 'Jhagadiya branch primary', 'Zagadiya Kumar Primary', 'Ranipura P.S.', 'Limbodara Primary');

**Comment by adamsanadi6** [comment]
I have made the changes as requested in the review. [Here is the ticket link for reference](https://avni.freshdesk.com/a/tickets/3546).
