### ISSUE TITLE
[SR Card 5] Report - Prevalence of Anemia

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/Adolescent-Sewa-Rural#25]
## Context 
Current report is created using the avni-reporting tool, it is hard to add filters and drill down to existing format. This causes data trust and hard to maintain for developers.

## Tech tasks

- [x] Report format is [here](https://docs.google.com/spreadsheets/d/1ZCQRQ07Q0tLj48sW3TrHn2kAYJa2z5wX/edit#gid=1655784908&range=B5)
- [x] Filters required are [here](https://docs.google.com/spreadsheets/d/1ZCQRQ07Q0tLj48sW3TrHn2kAYJa2z5wX/edit#gid=1655784908&range=B3) 
- [x] Create corresponding line lists as required with the drill down functionality
- [x] Exclude all voided entities

**Comment by Dinesh2019** [comment]
- [x] Filter level is not updated as per the requirment
- [x] Linelist format is not updated as per the requirment

**Comment by adamsanadi6** [comment]
Link to the Reports:
1. [Prevalence of Anemia](https://reporting.avniproject.org/question/2987-prevalence-of-anemia-do-not-use)
2. [Prevalence of Anemia Linelist](https://reporting.avniproject.org/question/2995-prevalence-of-anemia-linelist-do-not-use)

**Comment by Dinesh2019** [comment]
We have a count mismatch between the aggregate and line list while applying the filter this is due to some issue from Metabase

**Comment by nupoorkhandelwal** [comment]
https://reporting.avniproject.org/dashboard/258-prevalance-of-anemia

**Comment by nupoorkhandelwal** [comment]
https://reporting.avniproject.org/dashboard/258-prevalance-of-anemia
