### ISSUE TITLE
[SR][Operational Reports] App Monitoring/Operational Dashboard - Registrations

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/Adolescent-Sewa-Rural#26]
## Requirement document 
https://docs.google.com/spreadsheets/d/1ZCQRQ07Q0tLj48sW3TrHn2kAYJa2z5wX/edit#gid=208134223&range=A4:A9

- [x] Title - Total Number of Individual Registration

Type - Count
Drill down - To the registration linelist
Join - Address table
Exclude - voided
Filter field : Registration date

- [x] Title - Registrations Line list

Type - Line list
Drill down - NA
Join - Address table
Exclude - voided
Filter field : Registration date

**Comment by pkundu** [comment]
@AnjaliBhagabati can you create separate cards for each of them

**Comment by adamsanadi6** [comment]
Dashboard Links:
1. [Operational Dashboard](https://reporting.avniproject.org/dashboard/260-operational-dashboard)

**Comment by nupoorkhandelwal** [comment]
@adamsanadi6 cancel visits are synced in different ETL tables. You will have to update this query to have cancelled data on dashboards. Join the cancel table with respective encounter table.

**Comment by nupoorkhandelwal** [comment]
@adamsanadi6 cancel visits are synced in different ETL tables. You will have to update this query to have cancelled data on dashboards. Join the cancel table with respective encounter table.
