### ISSUE TITLE
[ADSR Support] Debug & Fix a dashboard card rule failure

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/Adolescent-Sewa-Rural#27]
# Rule UUID
`9ecbc619-4e68-4e27-850e-7828743ae04e`

##Error Message 
**undefined is not a function**

##Tech task

- [ ] As per stacktrace there is some error in the card - Adolescents having addiction
- [ ] Fix it on UAT
- [ ] Once QA is done, move the change to prod
- [ ] Mark the rule failures as closed in the table
- [ ] Add details of what was the issue & resolution

**Comment by Gojo-Taqi** [comment]
There were changes made on 28-Feb by himesh on production.
I was not able to reproduce the issue as well, so it's more likely that rule failure happened while development.
Marking this card as closed.
