### ISSUE TITLE
Changes Go Live

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/Adolescent-Sewa-Rural#28]
## Moving changes to prod

- [x] Upload bundle without locations from UAT to production org
- [x] Run the scripts under - [Card 3](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/adolescent-sewa-rural/23) [Card 4](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/adolescent-sewa-rural/24)
- [x] Upload Gujarati translations from Lokalise to production org

**Comment by Dinesh2019** [comment]
- [ ] Reason for exit is not updated as expected 

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjRrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33a8c0d090a7310a8592ee99618fcf022b1cb39f/Screenshot%202024-04-01%20at%206.48.44%E2%80%AFPM.png" alt="Screenshot 2024-04-01 at 6.48.44 PM.png" />
