### ISSUE TITLE
[SR][CR230902] Change in Hb ranges for Anemia category

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Adolescent-Sewa-Rural#3]
**Context**
Based on the updated guidelines from WHO, the new value range of Hemoglobin to determine different categories of Anemia is as given below.
https://docs.google.com/spreadsheets/d/1umBm1lkuFNoHk-naE0uFV1ZAc6j02XC-rfV1rUauHHc/edit#gid=1277219951

**Goal**
1. Update the decision rule for Moderate Anemia, Severe Anemia, Mild Anemia and Non Anemic in following forms:
- Annual visit - Baseline
- Annual visit - Endline
- Moderate Anemia follow-up
- Severe Anemia follow-up
2. Update Program Summary for Anemia status.
3. Update visit scheduling rule for Moderate Anemia follow-up and Severe Anemia follow-up in the following forms:
- Annual visit - Baseline
- Annual visit - Endline
- Moderate Anemia follow-up
- Severe Anemia follow-up
4. Update dashboard card for Moderate and Severe Anemia.

**Organizations:**
UAT - Adolescent Sewa Rural UAT
Prod - Adolescent Sewa Rural

**Comment by salilsamanvay** [comment]
@salilsamanvay Visit previously scheduled as per old logic will reflect as per previous Anemia status only, next visit after the changes are implemented will be scheduled as per modified anemia logic. need to communicate this to client when showcasing the changes.
