### ISSUE TITLE
[SR][Operational Dashboard] Completed visits

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/Adolescent-Sewa-Rural#34]
## Requirement doc 
https://docs.google.com/spreadsheets/d/1ZCQRQ07Q0tLj48sW3TrHn2kAYJa2z5wX/edit#gid=208134223&range=A27:A32

## For every visit type

- [x] Title - **Completed visits**

Type - Count of completed visits by Visit type
Drill down - To the completed visits linelist
Join - Individual & Address table
Exclude - voided
Filter field : Earliest visit date

**Comment by pkundu** [comment]
@nupoor changing the heading. Avoid naming like - card 1, card 2 etc
