### ISSUE TITLE
Adolescent Sewa Rural: Dashboard & Reports: Prevalence of Anaemia

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#38]
- [x] This is a dashboard report which has an aggregate and a linelist report that needs to be added for clients in Metabase.
 - [x] Exited as "No" should be a default option.
 - [x] Void the 2 existing prevalence of anaemia from Metabase, which are listed below. 
- Service Delivery Reports > [Prevalence of Anaemia](https://reporting.avniproject.org/dashboard/258-prevalance-of-anemia) for these reports also remove [aggregate](https://reporting.avniproject.org/question/2987-prevalence-of-anemia) and [linelist](https://reporting.avniproject.org/question/2995-prevalence-of-anemia-linelist) from Reports for dashboards.
- Vulnerability Prevalence Reports > [Prevalence of Anaemia](https://reporting.avniproject.org/question/2339-prevalence-of-anemia)

 - [x] **Filters available**
1. Enrolment Start Date
2. Enrolment End Date
3. Gender
4. Age group
4. Exited
5. Village
6. School
7. Boarding
8. HB Category (Linelist only)

 - [x] **Linelist Columns**
Individual Id
Name
Gender
DOB
Age
Date of Registration
Date of Enrolment
Date of Exit
Date of Latest HB Recorded
HB Value
School
Boarding
Village
Exited
Link to DEA

 - [x] **Age Group**
 **Less than 10**
10 -13
14-17
18-19
Above 19

 - [x] **HB Values**

- [x] <= 7.9
- [x] 8 - 10.9
- [x] 11 - 11.9
- [x] 12 - 12.9
- [x] >= 13

**Description to be added for this report:**

- [x] Total adolescents enrolled = (HB recorded + HB not recorded)
- [x] HB recorded = The sum of all children with HB values within these ranges <= 7.9, 8 - 10.9, 11 - 11.9, 12 - 12.9 and > =13. These values are being fetched from the latest encounter.
- [x] HB not recorded = Total adolescent enrolled - HB recorded. These values are being fetched from the latest encounter.
- [x] The count of children who have exited the program can be determined using the Exited filter. **However, by default, the data reflects only the active adolescents in the program.**
- [x] Filter - HB Category will only filter the data available in linelist and will not impact the aggregate data.

****Folder Structure** - Adolescent Sewa Rural New > Vulnerability Prevalence Reports**

-----

- [ ] Instead of requiring users to download the CSV file with the larger count in the line list and validate it separately, is there an alternative method we can implement at the UI level to facilitate easier validation for users

**Comment by Dinesh2019** [comment]
Please consider this requirement too.

Requirement :

- [ ] Instead of requiring users to download the CSV file with the larger count in the line list and validate it separately, is there an alternative method we can implement at the UI level to facilitate easier validation for users
- [ ] We have the count mismatch when applying with age filter due to some individual age is less than 10

**Comment by Dinesh2019** [comment]
Please consider this requirement too.

- [ ] 
Requirement :

- [ ] Instead of requiring users to download the CSV file with the larger count in the line list and validate it separately, is there an alternative method we can implement at the UI level to facilitate easier validation for users
- [ ] We have the count mismatch when applying with age filter due to some individual age is less than 10

**Comment by adamsanadi6** [comment]
[Dashboard link](https://reporting.avniproject.org/dashboard/268)

**Comment by kameshbhariya** [comment]
@adamsanadi6 Age range "Less than 10" needs to be added in age filter.

**Comment by Dinesh2019** [comment]
@adam once this is fixed move the card back to IN QA.

**Comment by adamsanadi6** [comment]
@Dinesh2019 @kameshbhariya Updated the Age Group.

**Comment by kameshbhariya** [comment]
@Dinesh2019 "However, by default, the data reflects only the active adolescents in the program." This has been added in the 4th description point now, please test this as well.
