### ISSUE TITLE
Adolescent Sewa Rural: Dashboard & Reports: Prevalence of Anaemia (Baseline & Endline Aggregate and Baseline & Endline Linelist Report)

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#39]
- [x] This is a dashboard report which has an aggregate and a linelist report that needs to be added for clients in Metabase.
- [x] Representation of reports in Metabase - <img width="706" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHZDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f0286c017e8530450de260585c50142d6052ae0/Screenshot%202024-05-08%20at%2012.58.30%E2%80%AFPM.png" alt="Screenshot 2024-05-08 at 12.58.30 PM.png" />

- [x] Exited as "No" should be a default option.
- [x] [Link to Analysis](https://docs.google.com/spreadsheets/d/1jtD256txy-sK_mwJZxEjbeeickTE5gb1/edit#gid=4743718)

---------------

- [ ] Refer sheet for description to be added for this report.

--------------

- [x] ****Folder Structure** - Adolescent Sewa Rural New > Vulnerability Prevalence Reports**

**Comment by adamsanadi6** [comment]
[Dashboard link](https://reporting.avniproject.org/dashboard/268)

**Comment by kameshbhariya** [comment]
@adamsanadi6 @Dinesh2019 There are some changes in this card, please look into it.
Sickle Cell Disease column needs to be added in linelist for this card.

**Comment by Dinesh2019** [comment]
@adamsanadi6 can you complete the new changes and move it back to QA ready

**Comment by adamsanadi6** [comment]
@Dinesh2019 @kameshbhariya New Changes are
- [x] New 2 filters added
1. HB Recorded Start Date
2. HB Recorded End Date

- [x] Updated the 'HB Category' indicator name from 'Total Adolescents Enrolled'(old) to 'Total Adolescents Encounter'(new).
- [x] Updated the Percentage formula.
- [x] Added Description in Baseline and Endline tab.
- [x] Updated the Description in Latest tab.
- [x] Added the new Column 'Sickle Cell Disease' in Baseline and Endline linelist. (Options: Test not performed, Negative, Trait and Disease)

**Comment by Dinesh2019** [comment]
- [ ] Description is not as per the requirement

**Comment by adamsanadi6** [comment]
@kameshbhariya Please update the Description requirement both in Card and In Requirement sheet. cc: @Dinesh2019
