### ISSUE TITLE
Adolescent Sewa Rural: Dashboard & Reports: Menstrual Disorder (Baseline & Endline Aggregate and Linelist Report))

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#40]
- [x] This is a dashboard report which has an aggregate and a linelist report that needs to be added for clients in Metabase.
- [x]  Representation of reports in Metabase -
 <img width="386" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUxDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4cde2d7592d38608a40dda4f27f70ef3c7e8b4af/Screenshot%202024-05-08%20at%201.08.29%E2%80%AFPM.png" alt="Screenshot 2024-05-08 at 1.08.29 PM.png" />

- [x] Exited as "No" should be a default option.
- [x] Void the [existing report](https://reporting.avniproject.org/question/2317-prevalence-of-menstrual-disorders) available in Vulnerability Prevalence Reports.
- [x] [Link to Analysis](https://docs.google.com/spreadsheets/d/1jtD256txy-sK_mwJZxEjbeeickTE5gb1/edit#gid=716093645)

---------------

- [x] **Refer sheet for Description to be added for this report**

--------------

- [x] ****Folder Structure** - Adolescent Sewa Rural New > Vulnerability Prevalence Reports**

**Comment by vedfordev** [comment]
Dashboard Link : [Dashboard](https://reporting.avniproject.org/dashboard/280-menstrual-disorder)

**Comment by vedfordev** [comment]
@nupoorkhandelwal Please check it.

**Comment by Dinesh2019** [comment]
- [ ] Menstrual Absorbent and Menstrual Disorder The Menstruation Started count is different for endline in each report.
- [x] We need to add the column named Visit start date or encounter date.
- [x] Header for endline and description should be aligned properly
- [ ] We have the count mismatch

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekR6QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ba0eda1e5e7925dfcd62c87ef09a1328e894fba/Screenshot%202024-05-20%20at%207.42.43%E2%80%AFAM.png" alt="Screenshot 2024-05-20 at 7.42.43 AM.png" />

- [x] We can have age column alone and we can remove the age group column
- [x] Description is not as per the requirement @Dinesh2019 **the description is mostly managed by the BA, and not added by dev. And over here, the description on the card is not right, it was changes after several discussions. So you can ignore this point.**

**Comment by nupoorkhandelwal** [comment]
@Dinesh2019 as discussed, can you please check and share exact details on the count mismatch that you have pointed.
