### ISSUE TITLE
Adolescent Sewa Rural: Dashboard & Reports: Menstrual Absorbent Used (Baseline & Endline Aggregate and Baseline & Endline Linelist Report)

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#41]
- [x] This is a dashboard report which has an aggregate and a linelist report that needs to be added for clients in Metabase.
- [x]  Representation of reports in Metabase -
<img width="444" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNS9DQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9c876e18d5e8322b4f7f7c134133d8405fe3849/Screenshot%202024-05-08%20at%201.16.35%E2%80%AFPM.png" alt="Screenshot 2024-05-08 at 1.16.35 PM.png" />

- [x]  Menstruating adolescent girls can use multiple absorbent materials, so the count of each absorbent used increases in each absorbent and so does the count in reports increase.
- [x] Exited as "No" should be a default option.
- [x] [Link to Analysis](https://docs.google.com/spreadsheets/d/1jtD256txy-sK_mwJZxEjbeeickTE5gb1/edit#gid=2110866201)

---------------

- [x] **Refer sheer for description to be added for this report:**
--------------

- [x] ****Folder Structure** - Adolescent Sewa Rural New > Vulnerability Prevalence Reports**

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal please review this.

**Comment by adamsanadi6** [comment]
[Dashboard link](https://reporting.avniproject.org/dashboard/281)

**Comment by Dinesh2019** [comment]
- [ ] Description doesn't match as per the requirement 

> **The description is updated in the reports and not in the card or req sheet. So it is a miss by BA. You can ignore it.**

- [ ] And we have the count mismatch for All menstruating girls in the endline line list 

> **As discussed for this, please confirm once more.**


- [x] We have the add the line list only text in the filter which is applied in linelist alone
- [x] Do we need the add the encounter date

**Comment by Dinesh2019** [comment]
@nupoorkhandelwal In the aggregate of endline report we have the count of 2622 for All menstruating girls but when we download the Excel it shows a different count.

Video for references :


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2J6QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73d57537cc2eb274a65dda7cc71eed7c8e663a4b/Screen%20Recording%202024-05-20%20at%201.40.42%E2%80%AFPM.mov

**Comment by Dinesh2019** [comment]
Still we have the count mismatch

**Comment by kameshbhariya** [comment]
@Dinesh2019 Refer sheet for descriptions in the report. I'll update the same for other reports as well.

**Comment by pkundu** [comment]
@kameshbhariya please update the description in the report itself. let us not ask Dinesh to refer to the sheet for testing

**Comment by Dinesh2019** [comment]
- [ ] we have to add the filter for date of recording  @Dinesh2019 it is not part of the requirement.
