### ISSUE TITLE
Adolescent Sewa Rural: Dashboard & Reports: Malnutrition (Baseline & Endline Aggregate and Baseline & Endline Linelist Report)

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#42]
- [ ] This is a dashboard report which has an aggregate and a linelist report that needs to be added for clients in Metabase.
- [ ]  Representation of reports in Metabase -
<img width="594" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2JDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df79aae7e03162f49eff3316895dfc1d162c8431/Screenshot%202024-05-08%20at%201.24.56%E2%80%AFPM.png" alt="Screenshot 2024-05-08 at 1.24.56 PM.png" />
- [ ] Exited as "No" should be a default option.
- [ ] [Link to Analysis](https://docs.google.com/spreadsheets/d/1jtD256txy-sK_mwJZxEjbeeickTE5gb1/edit#gid=797197741)

---------------

- [ ] **Refer sheet for Description to be added for this report**

--------------

- [ ] ****Folder Structure** - Adolescent Sewa Rural New > Vulnerability Prevalence Reports**

**Comment by nupoorkhandelwal** [comment]
@petmongrels can you please review this [report](https://reporting.avniproject.org/dashboard/279-prevalence-of-malnutrition?exited=No&(line_list_filter_only)_bmi_category_=Total%20Adolescents%20Encounter)

**Comment by Dinesh2019** [comment]
- [x] In the description we have given the BMI value as <14.5 but in the aggregate, we have mentioned it as <=14.5
- [x] In the requirement sheet in the line list we have the column referring to Type of Malnutrition but in the report we missed this column 
- [x] if we have the lower values then the total value is not displayed

**Comment by Dinesh2019** [comment]
- [ ] Date of Latest HB Recorded Is added in the malnutrition which is not needed in the Malnutrition report
- [ ] need to remove the age group column from the report
