### ISSUE TITLE
Adolescent Sewa Rural: Dashboard & Reports: Service Delivery Report (Baseline & Endline Aggregate and Baseline & Endline Linelist Report)

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#45]
- [x] This is a dashboard report which has an aggregate and a linelist report that needs to be added for clients in Metabase.
- [x] Exited as "No" should be a default option.
- [x] [Link to Analysis](https://docs.google.com/spreadsheets/d/1jtD256txy-sK_mwJZxEjbeeickTE5gb1/edit#gid=1256831118)

--------------

- [ ] Refer sheet for description to be added for this report.

-----------

- [ ] ****Folder Structure** - Adolescent Sewa Rural New > Service delivery reports**

**Comment by sachsk** [comment]
dashboard link: https://reporting.avniproject.org/dashboard/284-service-delivery-dashboard?year=2024

**Comment by Dinesh2019** [comment]
As discussed we are missing some requirements in the report please review it once and can you fix those changes as per the requirment.

**Comment by sachsk** [comment]
@Dinesh2019 we cant add the exit filter and referral in the report.

**Comment by Dinesh2019** [comment]
As discussed with Sachin Is adolescent referred? is taken from different places we haven't added in the column instead we asked to refer to the separate linelist and the Referral reason is not added in the prod It is still in UAT so this one is not added in the report.
