### ISSUE TITLE
Adolescent Sewa Rural: Dashboard & Reports: Exit Reason (Baseline & Endline Aggregate and Baseline & Endline Linelist Report)

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#46]
- [x] This is a dashboard report which has an aggregate and a linelist report that needs to be added for clients in Metabase.
- [x]  Representation of reports in Metabase - <img width="828" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeERnQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20fa792d6f12bf280bec0f85eaefcfca15495abb/Screenshot%202024-05-15%20at%201.07.54%E2%80%AFPM.png" alt="Screenshot 2024-05-15 at 1.07.54 PM.png" />

- [x] [Link to Analysis](https://docs.google.com/spreadsheets/d/1jtD256txy-sK_mwJZxEjbeeickTE5gb1/edit#gid=294425005)

---------------

- [x] **Refer sheet for description to be added in this report.**

--------------

- [x] ****Folder Structure** - Adolescent Sewa Rural New > Service delivery reports**

**Comment by vedfordev** [comment]
@kameshbhariya where we have to create dashboard ? change the description as we discussed yesterday

**Comment by vedfordev** [comment]
@kameshbhariya / @nupoorkhandelwal  Please let me know where I have to create dashboard. For now move card to on hold

**Comment by vedfordev** [comment]
[Dashboard](https://reporting.avniproject.org/dashboard/283-exit-reason-dashboard)

**Comment by vedfordev** [comment]
@nupoorkhandelwal done with report check once

**Comment by vedfordev** [comment]
@petmongrels can you review once?

**Comment by Dinesh2019** [comment]
@vedfordev When we apply the date filter for enrollment we have the count mismatch between agg and line list
also if we applied exit and enrol date the report crashed.

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVloQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d74127c5ec506354243038b6f958a87298a02188/Screenshot%202024-05-30%20at%2011.19.28%E2%80%AFAM.png" alt="Screenshot 2024-05-30 at 11.19.28 AM.png" />
