### ISSUE TITLE
[Adolescent Sewa Rural]: Changes in Baseline and Endline Form - May 2024

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#48]
- [ ] *[*Baseline Form Link**](https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=1232560057)

- [x] Under Referral Details > add a question and concept as "Referral Reason"  and add these drop-down option.
Sickle Disease
Severe Anemia
Modearte Anemia
Severe Malnutrition
Chronic Sickness
Menstrual Problem
Eye Problem
Skin Problem
Mental Health
Other. 
**If "Other" is selected, then provide a "Textbox"**

- [ ] Under Sexual Details > Add a question and concept at the last concept: "Do you suffer from itching in the perineal region?"

-------

- [ ] *[*Endline Form Link**](https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=1065000711)

- [x] In endline form, under Health Information > Medical Details, rename this ""Iron tablets consumed in last 3 month"" to: ""Total iron tablets consumed after baseline"". Accept values up to 3 digits

- [x] Under Referral Details > add a question and concept as "Referral Reason"  and add these drop-down option.
Sickle Disease
Severe Anemia
Modearte Anemia
Severe Malnutrition
Chronic Sickness
Menstrual Problem
Eye Problem
Skin Problem
Mental Health
Other. 
**If "Other" is selected, then provide a "Textbox"**

- [x] Under Sexual Details > Add a question and concept at the last concept: "Do you suffer from itching in the perineal region?"

**Comment by Dinesh2019** [comment]
@kameshbhariya I Tested only the AC written in the card and I found a column highlighted in green in the sheet  do let us know if we need to apply those changes as well if so can reopen the card again
