### ISSUE TITLE
[Adolescent Sewa Rural]: New Form Mental Health Followup & Counselling - May 2024

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#49]
- [x] Add the new program encounter in UAT 
- [x] [Mental Health Followup & Counselling] (https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=1010935732)

**Comment by Dinesh2019** [comment]
@kameshbhariya can you give me the visit schedule logic card link so that I can test the entire flow

**Comment by kameshbhariya** [comment]
@Dinesh2019 [Visit Scheduling Logic](https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=250931016)

**Comment by Dinesh2019** [comment]
@kameshbhariya did we create the card for this schedule logic to develop  if so can add the link of the card

**Comment by kameshbhariya** [comment]
Yes @Dinesh2019 

On the completion of Annual Visit - Baseline Encounter, schedule a Mental Health Follow-up when,
"Is her behaviour different from others?
Is she slower than others in learning and understanding new things?
Is there any developmental delay or disability seen?
If yes in any of the above 3 then mental health problem."

This forms due date will be 6 months from baseline encounter date and overdue date will be 30 days.

The same is mentioned here [Visit Scheduling Logic](https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=250931016)

**Comment by Dinesh2019** [comment]
@kameshbhariya According to your visit scheduling logic, there is only a single scheduling rule for mental health follow-up. Can you confirm if this is intended to be a one-time scheduling encounter? If not, we may need to address the visit scheduling logic to correct it.
