### ISSUE TITLE
[Adolescent Sewa Rural]: Visit Schedule - On the completion of Annual Visit - Baseline Encounter - May 2024

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#52]
The changes are marked in RED.

- [x] Make the changes in UAT.

[Visit Schedule Link](https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=250931016)

- [x] On the completion of Annual Visit - Baseline Encounter, the overdue date for Severe Anaemia Follow-up should be updated to 7 days when HB<8.
- [x] On the completion of Annual Visit - Baseline Encounter, the overdue date for Moderate Anaemia Follow-up should be updated to 7 days when HB >= 8 and HB < 11.
- [x] On the completion of Annual Visit - Baseline Encounter, the overdue date for Chronic Sickness Follow-up should be updated to 7 days when "Is there any other condition you want to mention about him/her" is answered as other than "No problem"
- [x] On the completion of Annual Visit - Baseline Encounter, the overdue date for Sickle Cell Disease Followup should be updated to 30 days, when "Sickling test result" is "Disease" and Earliest Visit Date should be updated to 6 months from baseline encounter date. If the earliest schedule date is falling after 1st Feb, then do not schedule followup.
- [x] On the completion of Annual Visit - Baseline Encounter, the overdue date for Severe Malnutrition Followup should be updated to 30 days, when BMI <= 14.5 and Earliest Visit Date should be updated to 6 months from baseline encounter date. If the earliest schedule date is falling after 1st Feb, then do not schedule followup.
- [x] On the completion of Annual Visit - Baseline Encounter, the overdue date for Menstrual Absenteeism Followup should be updated to 15 days, when the answer to "Does she remain absent during menstruation" = 'Yes'
- [x] On the completion of Annual Visit - Baseline Encounter, the overdue date for Addiction Followup should be updated to 30 days, when the answer to "Do you have any addiction" is answered as other than 'None’.
- [x] On the completion of Annual Visit - Baseline Encounter, **Remove** - School drop out encounter and its subsequent visit scheduling logic.
- [x] On the completion of Annual Visit - Baseline Encounter, schedule a Out of school followup form when, "Going to school" is answered as "Dropped out" and address level is "Village", then Out of school follow up form will open.
- [x] On the completion of Annual Visit - Baseline Encounter, schedule a Mental Health Follow-up when, 
"Is her behaviour different from others?
Is she slower than others in learning and understanding new things?
Is there any developmental delay or disability seen?
If yes in any of the above 3 then mental health problem."
This forms due date will be 6 months from baseline encounter date and overdue date will be 30 days.

**Comment by adamsanadi6** [comment]
@kameshbhariya Mental Health Follow-up scheduling logic is missing.
