### ISSUE TITLE
[Adolescent Sewa Rural]: Visit Schedule - On the completion of adolescent enrolment, the due date for Annual Visit - Baseline should be updated to 31st October, same year as enrolment. - May 2024

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#53]
- [x] Make the changes in UAT.
- [x] On the completion of adolescent enrolment, the due date for Annual Visit - Baseline should be updated to 31st October, same year as enrolment.
- [x] [Visit Schedule] (https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=250931016)
**Refer row 2 & 3**

**Comment by Dinesh2019** [comment]
@nupoorkhandelwal @kameshbhariya what happens if we register the individual after 31 October?

**Comment by Dinesh2019** [comment]
@kameshbhariya @adamsanadi6 as we discussed this scenario is not going to happen in the field.
