### ISSUE TITLE
[Adolescent Sewa Rural]: Update Nutritional Status Under Medical Details and Program Summary in Baseline and Endline Form - May 2024

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#59]
- [x] Make the changes in UAT.
- [x] Add Nutritional Status Under Medical Details and Program Summary in Baseline and Endline Form.
- [x] Nutritional Statuses are
Severe Malnourished
Moderate Malnourished
Mild Malnourished
Normal
Mild Obese
Moderate Obese
Severe Obese
- [x] [Baseline Link](https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=1232560057)
- [x] [Endline Link](https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=1065000711)

------------------------------------------------------------------------------------------------------------------------
### **Tech notes**

- [x] Create a new coded type concept "Nutritional status as per WHO" 
- [x] Add this as a new field in the Baseline and Endline form just below "BMI (kg/m²)"
- [x] Use the following to calculate the "Nutritional status as per WHO" 

`imports.common.calculateGrowthStatusForAdolescent({individual, weight, height, asOnDate})`

- [x]  The above will return result/grade as {zScore: 2} 
- [ ].  Now, based upon the zscore value, display status as text depending upon the ranges shared in requirement-
**Severe Malnourished: -3
Moderate Malnourished: -2
Mild Malnourished: -1
Normal: 0
Mild Obese: 1
Moderate Obese: 2
Severe Obese: 3**
- [x]  Update the decision rule to update the "Risk of" to show the  "Nutritional status as per WHO" 
- [x]  Update the program summary to display the latest  "Nutritional status as per WHO" based upon the new field
- [x]  Update/rename the current concept "Nutrition status" to "Nutrition status as per BMI" 
- [x]  Test the decision and program summary rules for this new change

**Comment by vedfordev** [comment]
@Dinesh2019 It will work in 8.1

**Comment by Dinesh2019** [comment]
[productbug](https://github.com/avniproject/avni-client/issues/1414)

**Comment by Dinesh2019** [comment]
as discussed with the vedant  Update the decision rule to update the "Risk of" to show the "Nutritional status as per WHO" is the wrong logic.
