### ISSUE TITLE
[Sewa Rural] Change in logic for Moderate and Severe Anemia

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Adolescent-Sewa-Rural#6]
Organization:
UAT - Adolescent Sewa Rural UAT
Prod - Adolescent Sewa Rural

**Use case**
Hb range for different anemia category has been updated. Please check the sheet below:
https://docs.google.com/spreadsheets/d/1umBm1lkuFNoHk-naE0uFV1ZAc6j02XC-rfV1rUauHHc/edit#gid=1277219951

Tasks:
- [x] Update the logic for decision rule for Moderate anemia, Severe Anemia and Mild anemia in following forms.
1. Annual visit - Baseline encounter
2.  Annual visit - Endline encounter
3.  Severe Anemia followup encounter
4.  Moderate Anemia follow up encounter

- [x] Update visit scheduling rule for Moderate anemia follow-up and Severe anemia follow-up in following forms.
1. Annual visit - Baseline encounter
2.  Annual visit - Endline encounter
3.  Severe Anemia followup encounter
4.  Moderate Anemia follow up encounter

- [x] Update Program summary rule.
- [x] Update the range in dashboard card for "Adolescents having Moderate anemia"
- [x] Update the range in dashboard card for "Adolescents with Severe anemia"
- [x] Write a data modification script to change the decisions for existing observations

**Acceptance criteria**
Anemia status should be updated correctly based on the Hb ranges given.

**Comment by vedfordev** [comment]
# Dev Test Scenario


### Visit Schedule

**individual :** Test Visit Schedule <br>

| Encounter | HB  | Severe Anemia Follow-up | Moderate Anemia Follow-up |
| --- | --- | --- | --- |
| Annual Visit-Baseline | 7.9 | ✓   | x   |
| Annual Visit-Baseline | 8   | x   | ✓   |
| Annual Visit-Baseline | 11  | x   | x   |
| Annual Visit-Baseline | 10  | x   | ✓   |
| Annual Visit-Baseline | 15  | x   | x   |
| | | | |
| Annual visit - Endline | 7.9 | ✓   | x   |
| Annual visit - Endline | 8   | x   | ✓   |
| Annual visit - Endline | 11  | x   | x   |
| Annual visit - Endline | 10  | x   | ✓   |
| Annual visit - Endline | 15  | x   | x   |
| | | | |
| Severe Anemia followup | 7.9 | ✓   | x   |
| Severe Anemia followup | 8   | x   | ✓   |
| Severe Anemia followup | 11  | x   | x   |
| Severe Anemia followup | 10  | x   | ✓   |
| Severe Anemia followup | 15  | x   | x   |
| | | | |
| Moderate Anemia followup | 7.9 | ✓   | x   |
| Moderate Anemia followup | 8   | x   | ✓   |
| Moderate Anemia followup | 11  | x   | x   |
| Moderate Anemia followup | 10  | x   | ✓   |
| Moderate Anemia followup | 15  | x   | x   |


---

**Comment by Dinesh2019** [comment]
In the Endline visit if we click the None for this Do you have addiction question still it schedules the Addiction follow-up 

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcTd1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--86ae227119bd888c1e651d1a42685cfe406a2ab0/Screen%20Recording%202023-09-29%20at%204.50.23%20PM.mov
