### ISSUE TITLE
[Adolescent Sewa Rural]: Visit Schedule - On the completion of Severe Anaemia Follow-up - May 2024

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#60]
> The changes are marked in RED.

- [x] Make the changes in UAT.

> [Visit Schedule](https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=250931016)

--------------------------------------------------------------------------------------------------------------------------

- [x] On the completion of Severe Anaemia Follow-up Encounter update the overdue date to 15 days for the Severe Anaemia Follow-up Encounter.

- [x] On the completion of Severe Anaemia Follow-up Encounter update the overdue date to 15 days for the Moderate Anaemia Follow-up Encounter.

**Comment by Dinesh2019** [comment]
The follow-up for severe and moderate anemia is required after 15 days, but the actual follow-up was done after only 3 days of being overdue
