### ISSUE TITLE
[Adolescent Sewa Rural]: Visit Schedule - On the completion of Moderate Anemia Follow-up - May 2024

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#61]
- [x] The changes are marked in RED.

- [x] Make the changes in UAT.

--------------------------------------------------------------------------------------------------------------------------

[Visit Schedule
](https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=250931016)

--------------------------------------------------------------------------------------------------------------------------
- [x] On the completion of Moderate Anaemia Follow-up Encounter update the overdue date to 15 days for the Severe Anaemia Follow-up Encounter.
- [x] On the completion of Moderate Anaemia Follow-up Encounter update the overdue date to 15 days for the Moderate Anaemia Follow-up Encounter.
- [x] Update the same in the Moderate Anaemia Follow-up Cancel Encounter as well

**Comment by Dinesh2019** [comment]
The follow-up for severe and moderate anemia is required after 15 days, but the actual follow-up was done after only 3 days of being overdue

Video Refrences:


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejBRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e7fe0123d258b2cd7a63d677c92ead25be890f5/Screen%20Recording%202024-05-26%20at%2010.48.10%E2%80%AFAM.mov
