### ISSUE TITLE
[Adolescent Sewa Rural]: Visit Schedule - On the completion of Menstrual Absenteeism Follow-up - May 2024

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#62]
The changes are marked in RED.

Make the changes in UAT.

[Visit Schedule
](https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=250931016)

- [x] On completion of "Menstrual Absenteeism Follow-up", just update the max date to 15 days instead of 3 days 
- [x] Also, add the scheduling logic on the cancellation of "Menstrual Absenteeism Follow-up" same as on completion. In all there should be only 3 followup visit of this encounter after Baseline/Endline from where it started

## Tech note -
The already existing condition seems to be completely fine -
`numberOfBaselineEncountersCompleted + numberOfEndlineEncountersCompleted ) * 3 > numberOfMenstrualAbsenteeismEncoutnersCompleted + 1 `

- [x] Just do a thorough testing of the same.

**Comment by vedfordev** [comment]
**back up of cancellation logic:**
```js
//SAMPLE RULE EXAMPLE
"use strict";
({ params, imports }) => {
  const programEncounter = params.entity;
  const scheduleBuilder = new imports.rulesConfig.VisitScheduleBuilder({ programEncounter });
  
      const earliestDate = imports.moment(programEncounter.earliestVisitDateTime || programEncounter.encounterDateTime).add(1,'year').month(9).date(1).toDate();
      scheduleBuilder.add({ name: "Menstrual Absenteeism Follow-up", encounterType: "Menstrual Absenteeism Follow-up", earliestDate: earliestDate, maxDate: imports.moment(earliestDate).add(1,'month').toDate() });
  
  
  return scheduleBuilder.getAll();
};
```

**Comment by Dinesh2019** [comment]
- [ ] while trying cancellation getting the invalid date and the app crashed 

<img width="342" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBellRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f7d51f6e69272d0dbe88bbe7d46f443dbe26692/Screenshot%202024-05-26%20at%207.24.42%E2%80%AFAM.png" alt="Screenshot 2024-05-26 at 7.24.42 AM.png" />

- [ ] We have to update the complete logic in cancel scenarios as well for now if I cancel these the visit schedule for n number of times.
