### ISSUE TITLE
[Adolescent Sewa Rural]: Visit Schedule - On the completion of Out of School Follow-up - May 2024

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#64]
> The changes are marked in RED.

> Make the changes in UAT.

> [Visit Schedule

](https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=250931016)

--------------------------------------------------------------------------------------------------------------------------

- [x] On the completion of Out of school follow-up update the **Overdue date >> "Earliest date + 30 days"** for the next Out of school follow-up (Note - earliest date is the date of scheduling the next visit)
- [x] Do not schedule visits in case of **Age >= 24**

**Comment by Dinesh2019** [comment]
The follow-up visit is scheduled again scheduled on the same date and also overdue is 60 days in the requirement 

Video references :


https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVlRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--755ecb84e113a9a66719c0c2d39cca49a81f0923/Screen%20Recording%202024-05-27%20at%207.20.11%E2%80%AFAM.mov

**Comment by Dinesh2019** [comment]
@nupoorkhandelwal @kameshbhariya @adamsanadi6 @vedfordev We don't have the cancel logic for this encounter if we need to have the cancel logic please reopen the ticket.
