### ISSUE TITLE
[Adolescent Sewa Rural]: Visit Schedule - On the completion of Chronic Sickness Followup - May 2024

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#66]
The changes are marked in RED.

Make the changes in UAT.

[Visit Schedule
](https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=250931016)

**Update following when a Chronic sickness followup is completed and the subsequent Chronic sickness followup is scheduled**
- [x] Change the overdue date to 7 days instead of 3 days

**Comment by vedfordev** [comment]
@nupoorkhandelwal In cancellation overdue is 1 month. Do we need to change?

**Comment by Dinesh2019** [comment]
- [ ] We have to update the complete logic in cancel scenarios as well for now if I cancel these the visit schedule for n number of times.
