### ISSUE TITLE
[Adolescent Sewa Rural]: Visit Schedule - On the completion of Addiction Followup - May 2024

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#67]
The changes are marked in RED.

Make the changes in UAT.

[Visit Schedule
](https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=250931016)

- [x] On the completion of Addiction Follow-up update the overdue date to 15 days instead of 3 days for the next/subsequent Addiction Follow-up visits

**Comment by vedfordev** [comment]
@Dinesh2019 Please check visit schedule by addiction followup

**Comment by Dinesh2019** [comment]
We have to update the complete logic in cancel scenarios as well for now if I cancel these the visit schedule for n number of times.
