### ISSUE TITLE
[ADSR] Data fix - Card 1 - Cancel visits April 2023 to March 2024

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/Adolescent-Sewa-Rural#69]
> ### **Updating script to remove the check to see if the earliest is after April 2023, instead we will run the script for all the visits before March 2024**

- [x] 1. Select all the visits where earliest date is before March 2024
- [x] **DO NOT INCLUDE Endline and Baseline visits**
- [x] 2. Include visits which have encounter and cancel date as null
- [x] 3. Update Query. set ->>

```
   a. SET cancel date = 31st May 2024
   b. SET cancel observations -- ""Reason for cancellation of visit"" as ""Other""
   c. SET cancel observations -- ""Other reason for cancellation of visit"" as ""SR Phase 2 May 2024 Data fix""
   d. last modified by
   e. last modified date
   f. manual update history
```

> Can be done irrespective before/after app changes

> [Analysis](https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=1855338938)

**Comment by vedfordev** [comment]
@nupoorkhandelwal Please check [Script](https://github.com/avniproject/data-fixes/blob/main/adsr/2024/cancel_visit_april_2023_to_march_2024.sql)

**Comment by nupoorkhandelwal** [comment]
@vedfordev update the earliest visit date check to either of below
```
  and earliest_visit_date_time >= '2023-04-01 00:00:00'
  and earliest_visit_date_time <= '2024-03-31 23:59:59'
```

OR 

 ```
 AND earliest_visit_date_time::date >= '2023-04-01'
  AND earliest_visit_date_time::date <= '2024-03-31'
```

Rest looks fine to me. Create a support ticket for the product team review.

**Comment by vedfordev** [comment]
[support ticket](https://avni.freshdesk.com/a/tickets/4081)

**Comment by nupoorkhandelwal** [comment]
@Dinesh2019 this has been done on Pre release env - ADSR org
