### ISSUE TITLE
[ADSR] Data fix - Card 2 - Update overdue for Baseline 2024

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/Adolescent-Sewa-Rural#70]
- [x] 1. Select all the visits "Annual Visit - Baseline" with earliest date as ~ "2024"
- [x] 2. Include visits which have encounter and cancel date as null
- [x] 3. Update Query. set ->>

  
```
   a. SET max visit date = 31st October 2024
   b. last modified by
   c. last modified date
   d. manual update history
```

> Can be done irrespective before/after app changes

> [Analysis](https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=1855338938)

**Comment by adamsanadi6** [comment]
[Freshdesk link](https://avni.freshdesk.com/a/tickets/4080)
[Script link](https://github.com/avniproject/data-fixes/blob/main/adsr/2024/Updated%20max_visit_date_time%20to%2031st%20October%20for%20Baseline%202024.sql)

**Comment by nupoorkhandelwal** [comment]
@Dinesh2019 this has been done on Pre release env - ADSR org
