### ISSUE TITLE
[ADSR] Data fix - Card 4 - Void all scheduled visits (not completed) School drop-out anytime

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/Adolescent-Sewa-Rural#72]
- [x] 1. Select all the visits of type "School drop-out visit"
- [x] 2. Update Query. set ->>

            a. SET is_voided as true
            b. last modified by
            c. last modified date
            d. manual update history

> Can be done after the app change if the form/encounter type  itself is going to be voided/deleted

> [Analysis](https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=1855338938)

**Comment by adamsanadi6** [comment]
[Freshdesk link](https://avni.freshdesk.com/a/tickets/4085)
[Script link](https://github.com/avniproject/data-fixes/blob/main/adsr/2024/Void%20all%20scheduled%20visits%20(not%20completed)%20School%20drop-out%20anytime.sql)

**Comment by nupoorkhandelwal** [comment]
@Dinesh2019 this has been done on Prod env - ADSR UAT
