### ISSUE TITLE
[Adolescent Sewa Rural]: App Dashboard - Divide the existing custom dashboard to two different dashboards named "Vulnerability Details" and "Adolescents to be Exited"

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#87]
Divide the existing custom dashboard into two different dashboards named "Vulnerability Details" and "Adolescents to be Exited."

1. Vulnerability Details Cards will include 
- [ ] Severe Anaemia
- [ ] Moderate Anaemia
- [ ] Sickle Cell
- [ ] Addiction
- [ ] Chronic Sickness
- [ ] Menstrual Disorder
- [ ] Severe Malnutrition
- [ ] Adolescents who dropped Out of School

2. Overall Statistics
- [ ] Adolescents Exited
- [ ] Active Adolescents

**Comment by Dinesh2019** [comment]
@nupoorkhandelwal 

- [ ] Adolescents (Active and Exited) need to create or rename the dashboard.
- [ ] Adolescents who dropped Out of School need to be removed from Vulnerabilities Cards will include and need to be added in Adolescents (Active and Exited)

Note: I tried to delete the Adolescents who dropped Out of School form the Vulnerabilities Cards but it is adding more cards under the same name can you review and let me it is a product bug?
