### ISSUE TITLE
[Adolescent Sewa Rural]: Visit Schedule - Update visit schedule logic, for Severe Malnutrition follow-up on the completion of baseline and endline, as per z score = -3.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#88]
Update visit schedule logic, for Severe Malnutrition follow-up on the completion of baseline and endline, as per z score = -3.

- [x] [On the completion of baseline](https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=250931016&range=15:15)

- [x] [On the completion of endline](https://docs.google.com/spreadsheets/d/1RTEnr_lxHPgo9DUNTHTXtsFmnnzcYNQa/edit#gid=250931016&range=58:58)

**Comment by Dinesh2019** [comment]
@adamsanadi6 can we remove the BMI value and display the Z score since the follow-up is scheduled as per the Z score. or else can we add the z score in the program summary

**Comment by Dinesh2019** [comment]
@adamsanadi6 @kameshbhariya  as discussed we are not showing the Z score vaue in the summary
