### ISSUE TITLE
Adolescent Sewa Rural: Dashboard & Reports: [Prevalence of Malnutrition - Nutritional Status](Baseline & Endline Aggregate and Baseline & Endline Linelist Report)

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#89]
- [x] This is a dashboard report which has an aggregate and a linelist report that needs to be added for clients in Metabase.
- [x]  Representation of reports in Metabase -
<img width="594" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2JDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df79aae7e03162f49eff3316895dfc1d162c8431/Screenshot%202024-05-08%20at%201.24.56%E2%80%AFPM.png" alt="Screenshot 2024-05-08 at 1.24.56 PM.png" />
- [x] Exited as "No" should be a default option.
- [x] [Link to Analysis](https://docs.google.com/spreadsheets/d/1jtD256txy-sK_mwJZxEjbeeickTE5gb1/edit#gid=636733566)

---------------

- [x] **Refer sheet for Description to be added for this report**

--------------

- [x] ****Folder Structure** - Adolescent Sewa Rural New > Vulnerability Prevalence Reports**

**Comment by adamsanadi6** [comment]
Dashboard link: [Prevalence of Malnutrition Based on Nutritional Status](https://reporting.avniproject.org/dashboard/286)

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal Can you do the code review.?
