### ISSUE TITLE
[Sewa Rural] Update cancel logic to check the HB value and then only schedule the right visit

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/Adolescent-Sewa-Rural#9]
there are visits scheduled in the system which are based on previous HB value criteria, once we change the HB value logic some visits will have to be canceled by field users, so we will have to edit the logic to check the HB value / current Anemia status to schedule next visit correctly as per updated scenario given in below sheet link:

https://docs.google.com/spreadsheets/d/1umBm1lkuFNoHk-naE0uFV1ZAc6j02XC-rfV1rUauHHc/edit#gid=1277219951

- [x] Update cancel logic to check the HB value and then only schedule the right visit
- Moderate Anemia Follow-up Encounter Cancellation
- Severe Anemia Follow-up Encounter Cancellation

**Comment by salilsamanvay** [comment]
@Dinesh2019 please ensure that all the changes are in line with epic level as well

**Comment by Dinesh2019** [comment]
Test scenarios : 

1. Create the individual as severe anemia with old logic and cancel the severe anemia with the latest logic will schedule the moderate anemia follow-up
2. Create the individual as severe anemia with old logic and cancel the severe anemia with old logic will schedule the severe anemia follow-up
3. Create the individual as moderate anemia with old logic and cancel the moderate  anemia with the latest logic will schedule the severe anemia follow-up
4. Create the individual as moderate anemia with old logic and cancel the moderate  anemia with the old logic will schedule the moderate anemia follow-up

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVllQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dad05d8d455e3545dcd08dfc69a5773f0cbc6756/Screen%20Recording%202023-10-10%20at%205.34.01%E2%80%AFPM.mov
