### ISSUE TITLE
[ADSR] Card 5 - Void all the existing visits for all the adolescents exited.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#90]
### Tech tasks -

- [x] Write a script to update program encounters
- [x] set cancel date, cancel reason, last modified id & last modified by
- [x] For all the individuals who have been exited from the respective program
- [x] Program encounter date and cancel is null
- [x] All visits will be included

**Comment by nupoorkhandelwal** [comment]
[Ticket](https://avni.freshdesk.com/a/tickets/4163)

[Script](https://github.com/avniproject/data-fixes/blob/main/adsr/2024/cancel_all_visits_for_exit_cases.sql)

**Comment by nupoorkhandelwal** [comment]
This is done on Pre release ADSR org.
