### ISSUE TITLE
Adolescent Sewa Rural: Dashboard & Reports: Task Completion Rate

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/Adolescent-Sewa-Rural#93]
- [ ] This is an aggregate only report that needs to be added for clients in Metabase. Add this reports in Severe Anaemia Task Completion Rate and rename the report name to Task Completion Rate
- [ ] [Link to Analysis] (https://docs.google.com/spreadsheets/d/1jtD256txy-sK_mwJZxEjbeeickTE5gb1/edit#gid=30012289)

- [x] 1. Severe Anaemia
- [x] 2. Moderate Anaemia
- [x] 3. Sickle Cell Disease
- [x] 4. Addiction 
- [x] 5. Menstrual Disorder 
- [x] 6. Chronic Sickness 
- [x] 7. Severe Malnutrition 
- [x] 8. Mental Health

- [ ] Need to add one more linelist and filter item, which is marked in red.

--------------

- [ ] Refer sheet for description to be added for this report.

-----------

- [ ] ****Folder Structure** - Adolescent Sewa Rural New > Service delivery reports**

**Tech notes**

- [ ] Create a new tab for each encounter type in the same dashboard - [link](https://reporting.avniproject.org/dashboard/285-severe-anaemia-task-completion-rate?exited=No&scheduled_visits_count_(line_list_filter_only)=1)
- [ ] Query will be same except respective encounter's etl table schema name.

**Comment by Dinesh2019** [comment]
@kameshbhariya In the card, we have mentioned 8 cards, but in the requirement sheet, we only have 6 cards. We need to add the missing report.
@sachsk @kameshbhariya we have added staff last modified by is missing ,vulnerabilities is missing

**Comment by vedfordev** [comment]
#### Code review comments:

1. For addiction and moderate anaemia aggregate not showing.
2. Link to dea in linelist not available. 


<img width="1482" alt="Screenshot 2024-07-12 at 11 38 08 AM" src="https://github.com/user-attachments/assets/11557169-6677-4ec9-84a1-b7a0731c0a5b">
<img width="1455" alt="Screenshot 2024-07-12 at 11 37 03 AM" src="https://github.com/user-attachments/assets/b3187eb3-e102-43da-9689-21271e2a3141">
